# Generated by Django 5.1.4 on 2025-03-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mri", "0002_mriimage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_hospital.jpg",
                null=True,
                upload_to="hospital_images/",
            ),
        ),
    ]
