# Generated by Django 5.1.4 on 2025-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mri", "0003_hospital_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="hospital_images/"
            ),
        ),
    ]
